FROM node:16-alpine as build
WORKDIR /app
COPY . .
COPY ./env/.env.prod ./.env

RUN npm install --omit=optional \
    && npm run prisma:migrate \
    && npm run build

FROM node:16-alpine as prod

WORKDIR /app
COPY --from=build /app/ .

ENV HOST=0.0.0.0
ENV PORT=80

EXPOSE 80

CMD ["node", "dist/main.js"]
