FROM node:16-alpine as build
WORKDIR /app
COPY . .
COPY ./env/.env.staging ./env/.env.prod

RUN npm install --omit=optional \
    && npm run build

FROM node:16-alpine as prod

WORKDIR /app
COPY --from=build /app/ .

ENV HOST=0.0.0.0
ENV PORT=8080

EXPOSE 8080

CMD ["node", "dist/main.js"]
